# Generated by Django 5.0.4 on 2024-04-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=15, verbose_name="Titulo")),
                ("description", models.TextField(verbose_name="Descripcion")),
                (
                    "image",
                    models.ImageField(upload_to="portfolio", verbose_name="Imagen"),
                ),
                ("link", models.URLField(max_length=180, verbose_name="URL")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "s",
            },
        ),
    ]
