# Generated by Django 5.0.4 on 2024-04-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created"],
                "verbose_name": "proyecto",
                "verbose_name_plural": "proyectos",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="content_code",
            field=models.TextField(
                blank=True, null=True, verbose_name="Codigo a incorporar"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(upload_to="projects", verbose_name="Imagen"),
        ),
        migrations.AlterField(
            model_name="project",
            name="link",
            field=models.URLField(
                blank=True, max_length=180, null=True, verbose_name="URL"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Titulo"),
        ),
    ]
