# Generated by Django 5.0.4 on 2024-04-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution",
                    models.CharField(max_length=100, verbose_name="Institución"),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
            ],
            options={
                "verbose_name": "Formación",
                "verbose_name_plural": "Formaciones",
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
            ],
            options={
                "verbose_name": "Experiencia",
                "verbose_name_plural": "Experiencias",
            },
        ),
        migrations.CreateModel(
            name="Knowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="knowledge_icons")),
            ],
            options={
                "verbose_name": "conocimiento",
                "verbose_name_plural": "conocimientos",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Habilidad")),
                ("description", models.TextField(verbose_name="Descripción")),
            ],
            options={
                "verbose_name": "Habilidad",
                "verbose_name_plural": "Habilidades",
            },
        ),
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="about_me",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, max_length=180, null=True, verbose_name="URL"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "content_code",
                    models.TextField(
                        blank=True, null=True, verbose_name="Codigo a incorporar"
                    ),
                ),
                (
                    "education",
                    models.ManyToManyField(
                        to="about_me.education", verbose_name="Formación"
                    ),
                ),
                (
                    "experience",
                    models.ManyToManyField(
                        to="about_me.experience", verbose_name="Experiencia"
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        to="about_me.skill", verbose_name="Habilidades"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sobre mí",
                "verbose_name_plural": "Sobre mí",
                "ordering": ["-created"],
            },
        ),
    ]
