# Generated by Django 5.0.4 on 2024-04-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_me", "0002_alter_aboutme_education_alter_aboutme_experience_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutme",
            name="education",
            field=models.ManyToManyField(
                blank=True, to="about_me.education", verbose_name="Formación"
            ),
        ),
        migrations.AlterField(
            model_name="aboutme",
            name="experience",
            field=models.ManyToManyField(
                blank=True, to="about_me.experience", verbose_name="Experiencia"
            ),
        ),
        migrations.AlterField(
            model_name="aboutme",
            name="skills",
            field=models.ManyToManyField(
                blank=True, to="about_me.skill", verbose_name="Habilidades"
            ),
        ),
    ]
