# Generated by Django 5.0.4 on 2024-04-25 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_me", "0003_alter_aboutme_education_alter_aboutme_experience_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutme",
            name="education",
        ),
        migrations.RemoveField(
            model_name="aboutme",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="aboutme",
            name="skills",
        ),
        migrations.AddField(
            model_name="aboutme",
            name="education",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="about_me.education",
                verbose_name="Formación",
            ),
        ),
        migrations.AddField(
            model_name="aboutme",
            name="experience",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="about_me.experience",
                verbose_name="Experiencia",
            ),
        ),
        migrations.AddField(
            model_name="aboutme",
            name="skills",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="about_me.skill",
                verbose_name="Habilidad",
            ),
        ),
    ]
