# Generated by Django 5.0.4 on 2024-04-26 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "about_me",
            "0004_remove_aboutme_education_remove_aboutme_experience_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutme",
            options={
                "ordering": ["-pk"],
                "verbose_name": "Sobre mí",
                "verbose_name_plural": "Sobre mí",
            },
        ),
        migrations.AlterModelOptions(
            name="knowledge",
            options={
                "ordering": ["-pk"],
                "verbose_name": "conocimiento",
                "verbose_name_plural": "conocimientos",
            },
        ),
    ]
