# Generated by Django 5.0.4 on 2024-09-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about_me", "0007_alter_aboutme_options_remove_aboutme_content_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutme",
            name="description",
        ),
    ]
