# Generated by Django 5.0.4 on 2024-09-12 21:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_me", "0010_fact_icon_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillDesc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tittle_section",
                    models.CharField(
                        default="Skills",
                        max_length=100,
                        verbose_name="Título de Sección",
                    ),
                ),
                (
                    "desc_section",
                    models.TextField(
                        default="Magnam dolores commodi suscipit...",
                        verbose_name="Descripción de Sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Descripcion de Habilidades",
                "verbose_name_plural": "Descripciones de Habilidades",
            },
        ),
        migrations.DeleteModel(
            name="Knowledge",
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": ["-pk"],
                "verbose_name": "Habilidad",
                "verbose_name_plural": "Habilidades",
            },
        ),
        migrations.RemoveField(
            model_name="skill",
            name="description",
        ),
        migrations.AddField(
            model_name="skill",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="skill_icons",
                validators=[core.models.validate_image_size],
                verbose_name="Imagen",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="percentage",
            field=models.IntegerField(blank=True, null=True, verbose_name="Porcentaje"),
        ),
        migrations.AddField(
            model_name="skill",
            name="skill_type",
            field=models.CharField(
                choices=[("hard", "Hard Skill"), ("soft", "Soft Skill")],
                default="soft",
                max_length=4,
                verbose_name="Tipo de Habilidad",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre Habilidad"),
        ),
    ]
