# Generated by Django 5.0.4 on 2024-09-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_me", "0011_skilldesc_delete_knowledge_alter_skill_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeDesc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tittle_section",
                    models.CharField(
                        default="Resume",
                        max_length=100,
                        verbose_name="Título de Sección",
                    ),
                ),
                (
                    "desc_section",
                    models.TextField(
                        default="Magnam dolores commodi suscipit...",
                        verbose_name="Descripción de Sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Descripcion de Currículum",
                "verbose_name_plural": "Descripciones de Currículum",
            },
        ),
        migrations.AlterModelOptions(
            name="education",
            options={
                "ordering": ["start_year"],
                "verbose_name": "Educacion",
                "verbose_name_plural": "Educaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="experience",
            options={
                "ordering": ["start_year"],
                "verbose_name": "Experiencia",
                "verbose_name_plural": "Experiencias",
            },
        ),
        migrations.AddField(
            model_name="education",
            name="degree",
            field=models.CharField(
                default="Academia", max_length=100, verbose_name="Grado"
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="end_year",
            field=models.IntegerField(blank=True, null=True, verbose_name="Año fin"),
        ),
        migrations.AddField(
            model_name="education",
            name="start_year",
            field=models.IntegerField(default=2000, verbose_name="Año inicio"),
        ),
        migrations.AddField(
            model_name="experience",
            name="company",
            field=models.CharField(
                default="Independiente", max_length=100, verbose_name="Compañia"
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="end_year",
            field=models.IntegerField(blank=True, null=True, verbose_name="Año fin"),
        ),
        migrations.AddField(
            model_name="experience",
            name="responsibilities",
            field=models.TextField(
                blank=True, null=True, verbose_name="Responsabilidades"
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="start_year",
            field=models.IntegerField(default=2000, verbose_name="Año inicio"),
        ),
        migrations.AlterField(
            model_name="education",
            name="institution",
            field=models.CharField(max_length=100, verbose_name="Instituto"),
        ),
        migrations.AlterField(
            model_name="experience",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Titulo"),
        ),
    ]
