# Generated by Django 5.0.4 on 2024-09-13 21:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_me", "0012_resumedesc_alter_education_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioDesc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tittle_section",
                    models.CharField(
                        default="Portfolio",
                        max_length=100,
                        verbose_name="Título de Sección",
                    ),
                ),
                (
                    "desc_section",
                    models.TextField(
                        default="Magnam dolores commodi suscipit...",
                        verbose_name="Descripción de Sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Descripcion de Portafolio",
                "verbose_name_plural": "Descripciones de Portafolio",
            },
        ),
        migrations.CreateModel(
            name="PortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Titulo del Proyecto"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Software", "Software"),
                            ("Audiovisual", "Audiovisual"),
                            ("Otros", "Otros"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Filtro",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Descripcion del Proyecto"),
                ),
                (
                    "image1",
                    models.ImageField(
                        upload_to="portfolio/",
                        validators=[core.models.validate_image_size],
                        verbose_name="Imagen 1",
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="portfolio/",
                        validators=[core.models.validate_image_size],
                        verbose_name="Imagen 2",
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="portfolio/",
                        validators=[core.models.validate_image_size],
                        verbose_name="Imagen 3",
                    ),
                ),
                ("client", models.CharField(max_length=100, verbose_name="Cliente")),
                ("project_date", models.DateField(verbose_name="Fecha")),
                (
                    "project_url",
                    models.URLField(
                        blank=True,
                        default="Proyecto Corporativo (No Disponible Público)",
                        null=True,
                        verbose_name="Link",
                    ),
                ),
            ],
        ),
    ]
