# Generated by Django 5.0.4 on 2024-09-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_me", "0013_portfoliodesc_portfolioitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        default="bi bi-briefcase",
                        help_text="Nombre del ícono (ej. bi bi-briefcase). Visita https://icons.getbootstrap.com/ para ver la lista completa de íconos.",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio",
                "verbose_name_plural": "Servicios",
            },
        ),
        migrations.CreateModel(
            name="ServicesDesc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tittle_section",
                    models.CharField(
                        default="Services",
                        max_length=100,
                        verbose_name="Título de Sección",
                    ),
                ),
                (
                    "desc_section",
                    models.TextField(
                        default="Magnam dolores commodi suscipit...",
                        verbose_name="Descripción de Sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Descripcion de Servicios",
                "verbose_name_plural": "Descripciones de Servicios",
            },
        ),
    ]
