# Generated by Django 5.0.4 on 2024-09-14 16:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about_me", "0014_service_servicesdesc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=100, verbose_name="Nombre del autor"),
                ),
                (
                    "author_position",
                    models.CharField(max_length=100, verbose_name="Posición del autor"),
                ),
                (
                    "testimonial_text",
                    models.TextField(verbose_name="Texto del testimonio"),
                ),
                (
                    "testimonial_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/",
                        validators=[core.models.validate_image_size],
                        verbose_name="Imagen del testimonio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimonio",
                "verbose_name_plural": "Testimonios",
            },
        ),
        migrations.CreateModel(
            name="TestimonialDesc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tittle_section",
                    models.CharField(
                        default="Testimonials",
                        max_length=100,
                        verbose_name="Título de Sección",
                    ),
                ),
                (
                    "desc_section",
                    models.TextField(
                        default="Magnam dolores commodi suscipit...",
                        verbose_name="Descripción de Sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Descripcion de Testimonios",
                "verbose_name_plural": "Descripciones de Testimonios",
            },
        ),
    ]
